version: "3.7"
services:
    ingest:
        build:
            context: .
            dockerfile: redditrepostsleuth/ingestsvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - CELERY_IMPORTS=redditrepostsleuth.core.celery.ingesttasks

    admin_svc:
        build:
            context: .
            dockerfile: redditrepostsleuth/adminsvc/Dockerfile
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        environment:
            - LOG_LEVEL=INFO

    hot_post:
        build:
            context: .
            dockerfile: redditrepostsleuth/hotpostsvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
        entrypoint: python -u /src/redditrepostsleuth/hotpostsvc/hotpostsvc.py
        volumes:
            - /opt/imageindex:/opt/imageindex

    summons_svc:
        build:
            context: .
            dockerfile: redditrepostsleuth/summonssvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
        entrypoint: python -u /src/redditrepostsleuth/summonssvc/summonssvc.py

    stat_monitor_svc:
        build:
            context: .
            dockerfile: redditrepostsleuth/monitorsvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
        entrypoint: python -u /src/redditrepostsleuth/monitorsvc/monitorsvc.py

    summons_handler:
        build:
            context: .
            dockerfile: redditrepostsleuth/summonssvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
        entrypoint: python -u /src/redditrepostsleuth/summonssvc/summons_handler_svc_celery.py
        volumes:
            - /opt/imageindex:/opt/imageindex

    summons_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/repost/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
            - CELERY_IMPORTS=redditrepostsleuth.core.celery.response_tasks
        entrypoint: celery -A redditrepostsleuth.core.celery worker -Q summons -c 3
        volumes:
            - /opt/imageindex:/opt/imageindex

    subreddit_monitor:
        build:
            context: .
            dockerfile: redditrepostsleuth/submonitorsvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
        entrypoint: python -u /src/redditrepostsleuth/submonitorsvc/sub_monitor_svc_celery.py
        volumes:
            - /opt/imageindex:/opt/imageindex

    submonitor_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/repost/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
            - CELERY_IMPORTS=redditrepostsleuth.core.celery.response_tasks
        entrypoint: celery -A redditrepostsleuth.core.celery worker -Q submonitor -c 6
        volumes:
            - /opt/imageindex:/opt/imageindex

    ingest_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/ingest/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - C_FORCE_ROOT=True
            - CELERY_IMPORTS=redditrepostsleuth.core.celery.ingesttasks
            #- HASH_API=http://157.230.64.152:8000/hash
        entrypoint: celery -A redditrepostsleuth.core.celery worker -Q postingest -c 10

    generic_repost_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/repost/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
            - CELERY_IMPORTS=redditrepostsleuth.core.celery.reposttasks,redditrepostsleuth.core.celery.ingesttasks
        entrypoint: celery -A redditrepostsleuth.core.celery worker -Q repost,repost_link -c 1

    image_repost_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/repost/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - C_FORCE_ROOT=True
            - CELERY_IMPORTS=redditrepostsleuth.core.celery.reposttasks,redditrepostsleuth.core.celery.ingesttasks
        entrypoint: celery -A redditrepostsleuth.core.celery worker -Q repost_image -c 2
        volumes:
            - /opt/imageindex:/opt/imageindex

    deleted_post_cleanup_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/repost/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - C_FORCE_ROOT=True
            - CELERY_IMPORTS=redditrepostsleuth.core.celery.reposttasks,redditrepostsleuth.core.celery.maintenance_tasks
            - UTIL_API=http://167.99.22.106:8000
        entrypoint: celery -A redditrepostsleuth.core.celery worker -Q delete -c 2


    ingest_pushshift_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/ingest/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
            - CELERY_IMPORTS=redditrepostsleuth.core.celery.ingesttasks
        entrypoint: celery -A redditrepostsleuth.core.celery worker -Q pushshift -c 2

    pushshift_archive_intake_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
        entrypoint: celery -A redditrepostsleuth.common worker -Q pushshift_intake -c 1

    pushshift_archive_ingest:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
        entrypoint: celery -A redditrepostsleuth.common worker -Q pushshift_ingest -c 1
