version: "3.7"
services:
    ingest:
        build:
            context: .
            dockerfile: redditrepostsleuth/ingestsvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
            - CELERY_IMPORTS=redditrepostsleuth.core.celery.ingesttasks

    hot_post:
        build:
            context: .
            dockerfile: redditrepostsleuth/hotpostsvc/Dockerfile
        environment:
            - LOG_LEVEL=DEBUG
            - SLEUTHCONFIG=testconfig.ini
        entrypoint: python -u /src/redditrepostsleuth/hotpostsvc/hotpostsvc.py
        volumes:
            - /opt/imageindex:/opt/imageindex

    summons_svc:
        build:
            context: .
            dockerfile: redditrepostsleuth/summonssvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
        entrypoint: python -u /src/redditrepostsleuth/summonssvc/summonssvc.py

    stat_monitor_svc:
        build:
            context: .
            dockerfile: redditrepostsleuth/monitorsvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
        entrypoint: python -u /src/redditrepostsleuth/monitorsvc/monitorsvc.py

    summons_handler:
        build:
            context: .
            dockerfile: redditrepostsleuth/summonssvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
        entrypoint: python -u /src/redditrepostsleuth/summonssvc/summonshandlersvc.py
        volumes:
            - /opt/imageindex:/opt/imageindex

    subreddit_monitor:
        build:
            context: .
            dockerfile: redditrepostsleuth/submonitorsvc/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
        entrypoint: python -u /src/redditrepostsleuth/submonitorsvc/submonitorsvc.py
        volumes:
            - /opt/imageindex:/opt/imageindex

    ingest_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/ingest/Dockerfile
        environment:
            - LOG_LEVEL=DEBUG
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
            - CELERY_IMPORTS=redditrepostsleuth.core.celery.ingesttasks
        entrypoint: celery -A redditrepostsleuth.core.celery worker -Q postingest,repost,repost_link -c 1

    image_repost_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
        entrypoint: celery -A redditrepostsleuth.common worker -Q repost_image -c 1
        volumes:
            - /opt/imageindex:/opt/imageindex

    ingest_pushshift_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/Dockerfile
        environment:
            - LOG_LEVEL=DEBUG
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
        entrypoint: celery -A redditrepostsleuth.common worker -Q pushshift -c 1

    pushshift_archive_intake_worker:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
        entrypoint: celery -A redditrepostsleuth.common worker -Q pushshift_intake -c 1

    pushshift_archive_ingest:
        build:
            context: .
            dockerfile: redditrepostsleuth/workers/Dockerfile
        environment:
            - LOG_LEVEL=INFO
            - SLEUTHCONFIG=testconfig.ini
            - C_FORCE_ROOT=True
        entrypoint: celery -A redditrepostsleuth.common worker -Q pushshift_ingest -c 1
